language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # if you need to run emulator(s) during your tests

env:
  global:
  # install timeout: 8 minutes
  - ADB_INSTALL_TIMEOUT=8

before_script:

script:
  - ./gradlew test